### ISSUE TITLE
Manage list of experts on call not working as expected

### ISSUE THREAD

**Issue by tinsheep** [OfficeDev/microsoft-teams-apps-remotesupport#8]
I cant seem to manage the list of experts on call. I can click history which shows no history as expected but when i click manage i just get what looks like an empty task module window. I can create issues just fine. No deployment errors. thanks in advance.

![Annotation 2020-05-27 173524](https://user-images.githubusercontent.com/8007578/83085326-7df85800-a040-11ea-9d88-8a3539d078ba.jpg)

**Comment by rashmi-dixit** [comment]
How many members are part of this team?

**Comment by tinsheep** [comment]
There were two - i created a new app registration and reinstalled and its working now. thanks.
